// CARTOGRAFÍA ESTELAR 144 — cruces portal × punto natal (1 de 4).
//
// CAPA B. Pléyades, Sirio y Arcturus.
//
// ── QUÉ ES UN CRUCE ────────────────────────────────────────────────────────
// El tema del portal entrando por una función concreta de la experiencia.
// No es el portal más el punto: es lo que ocurre cuando ese tema se expresa
// justamente por ahí. Cada texto describe una dinámica, dice dónde puede
// observarse y señala qué se vuelve difícil en esa combinación concreta.
//
// Ninguno afirma lo que alguien es ni predice nada.

import type { PuntoNatalId } from "../domain/types"

export const CRUCES_1: Record<string, Record<PuntoNatalId, string>> = {
  pleyades: {
    sol: "La pertenencia no es aquí un asunto secundario: forma parte de aquello con lo que la persona se identifica. Suele traducirse en una noción de uno mismo que necesita estar en relación para reconocerse, y en la dificultad correspondiente para saber qué se quiere cuando no hay nadie delante. Lo delicado de esta combinación es que retirarse un tiempo no se vive como descanso sino como pérdida de referencia. Puede observarse en cómo respondes a quién eres cuando no puedes mencionar tu trabajo ni a las personas de tu vida.",
    luna: "La sensibilidad al estado ajeno entra por la vía menos deliberada, la que actúa antes de pensar. Puede manifestarse como estados de ánimo que cambian según con quién se ha estado, sin que haya causa propia identificable. Es la combinación en la que más cuesta distinguir lo propio de lo recogido, porque ambas cosas llegan por el mismo canal y con la misma intensidad. No hay un momento en que se decida absorber: ya ha ocurrido cuando se nota. Se observa mejor al final del día que durante, comparando el estado de ahora con el de la mañana.",
    mercurio: "El tema entra por cómo se piensa y se habla. Suele traducirse en una mente que registra lo no dicho en una conversación y trabaja con ello sin mencionarlo: se responde a lo que el otro quiso decir, no a lo que dijo. Aporta una comprensión fina y produce malentendidos cuando la suposición falla, porque nadie llegó a poner sobre la mesa lo que se estaba dando por hecho. Se observa en cuánto de lo que crees saber sobre alguien se lo has preguntado realmente, y en cuántas veces has respondido a algo que la otra persona no había llegado a decir.",
    venus: "El vínculo se convierte en el criterio principal de valor. Puede manifestarse como una facilidad poco común para entrar en relación y una dificultad para sostener el propio criterio dentro de ella: lo que se quiere se ajusta al tono compartido, a veces tan rápido que no queda registro de haber querido otra cosa. El ajuste no se siente como renuncia mientras ocurre; se nota después, al quedarse solo y no reconocer la decisión. Se observa al revisar elecciones tomadas con alguien delante y preguntarse cuál habría sido a solas.",
    marte: "La acción se activa en función del grupo. Suele traducirse en energía disponible cuando hay alguien a quien acompañar y dificultad para movilizarse por algo propio que no beneficia a nadie más. El límite y el conflicto son el punto delicado: decir que no se vive como poner en riesgo el vínculo, de modo que el no llega tarde, envuelto en explicaciones, o no llega. Se observa en cuánto tardas en decir que no cuando ya sabes que quieres decirlo, y en qué proyectos tuyos llevan meses parados mientras los ajenos avanzan.",
    jupiter: "El crecimiento llega por la vía de las personas. Puede manifestarse como una red amplia, oportunidades que aparecen por relaciones y una generosidad que no mide lo que se está comprometiendo. El riesgo es prometer desde el entusiasmo del encuentro y descubrir después que no cabía: en el momento de decir que sí, la relación pesa más que el calendario. Se observa en el número de compromisos adquiridos en conversación y sin consultar la agenda, y en cuántos de ellos has tenido que renegociar después.",
    saturno: "La pertenencia se vive como responsabilidad. Suele traducirse en sostener un grupo, una familia o un equipo durante años, con un sentido del deber que rara vez se cuestiona y que nadie formuló en voz alta. Puede dar una fiabilidad enorme y un cansancio que no se atribuye a nada concreto, porque no hay una tarea señalable: lo que agota es la atención sostenida. Se observa en qué sostienes que nadie te pidió que sostuvieras, y en qué pasaría en ese grupo si durante un mes dejaras de ocuparte de cómo está.",
    urano: "El tema entra por la vía de la diferencia. Puede manifestarse como una pertenencia incómoda: se necesita el grupo y a la vez algo propio no encaja en él, de modo que ni se está dentro del todo ni se puede prescindir. Suele producir cortes bruscos seguidos de regreso, porque la salida alivia la incomodidad pero no resuelve la necesidad. Se observa en el historial de grupos dejados y retomados, y en qué parte de ti sueles dejar fuera cuando decides quedarte.",
    neptuno: "Los bordes entre lo propio y lo ajeno se vuelven especialmente finos. Puede manifestarse como absorber el estado de una sala sin registro consciente de haberlo hecho, y como idealizar a un grupo o a una persona hasta no poder verla. Es la combinación en la que más conviene una práctica explícita de separación, porque la percepción no viene con etiqueta de origen. Se observa en qué sientes ahora mismo que no sabes de dónde sale, y en cuánto tarda en disolverse cuando cambias de entorno.",
    pluton: "La pertenencia se vuelve un asunto de fondo, sin término medio. Suele traducirse en vínculos intensos y en una sensibilidad alta a las dinámicas de poder dentro de un grupo: quién decide, quién queda fuera, qué no se dice. Puede aparecer también control sobre el propio círculo, en forma de vigilancia discreta sobre quién se acerca a quién. Se observa en qué situaciones de grupo te remueven más de lo que parecería razonable, y en qué haces cuando alguien cercano establece un vínculo nuevo que no te incluye.",
    nodo_norte: "La dirección menos automática pasa por aquí. Dentro de esta metodología señala que sostener la propia posición dentro de un vínculo, sin retirarse ni disolverse, es el territorio que enseña. No suele sentirse natural al principio: lo que aparece primero es la sensación de estar rompiendo algo, no la de estar apareciendo. Se observa en qué conversaciones pospones porque implicarían decir algo que rompe el tono, y en cuántas veces has elegido el silencio para que el ambiente no cambiara.",
    nodo_sur: "El terreno practicado es leer a la gente. Es un recurso real y disponible —se entra en una sala y se sabe cómo está— y también el sitio al que se vuelve cuando algo aprieta: ocuparse del estado de otro es una manera muy eficaz de no mirar el propio, y además se recibe como generosidad. Por eso cuesta detectarlo desde dentro. Se observa en qué haces cuando tienes una decisión difícil pendiente, y en cuántas de tus conversaciones recientes trataron sobre la vida de otro y no sobre la tuya.",
    ascendente: "El tema está en la puerta. Suele traducirse en entrar en las situaciones percibiendo primero el ambiente y ajustándose a él, muchas veces antes de haber decidido nada. Produce una presencia que la gente encuentra fácil y una dificultad para aparecer con algo propio desde el principio: cuando llega el momento de decir lo que uno quiere, el tono ya está puesto y contradecirlo cuesta más. Se observa en cómo entras en un sitio donde no conoces a nadie, y en cuánto tardas en decir algo que no siga la corriente.",
    medio_cielo: "La aportación pública pasa por el tejido entre personas. Puede manifestarse como un trabajo o un papel donde lo que se hace es sostener el vínculo de un grupo, con frecuencia sin que esa función tenga nombre ni figure en ninguna descripción de tareas. Eso trae un reconocimiento difuso: se nota cuando falta y no cuando está. Se observa en para qué te busca la gente más allá de tu cargo, y en qué se descolocaría en tu entorno si durante un mes hicieras solo lo que pone en tu contrato.",
  },

  sirio: {
    sol: "La identidad se construye alrededor de lo que se sostiene. Suele traducirse en reconocerse a uno mismo por la propia tarea, con la solidez que eso da y la fragilidad correspondiente: si el valor queda atado a la utilidad, dejar de ser útil se parece demasiado a dejar de valer. Los periodos sin trabajo claro no se viven como descanso sino como una pérdida de contorno. Se observa en cómo respondes a quién eres cuando no puedes mencionar lo que haces, y en qué sientes un domingo sin nada pendiente.",
    luna: "La disciplina entra por la vía emocional. Puede manifestarse como una necesidad de orden y de tarea para estar tranquilo: el trabajo calma y la falta de estructura inquieta, de modo que ponerse a hacer algo funciona como regulación del ánimo antes que como producción. Produce constancia real y dificultad para descansar sin haberlo justificado con un esfuerzo previo. Se observa en qué haces cuando algo te remueve, y en si el descanso llega por decisión o solo cuando el cuerpo lo impone.",
    mercurio: "El tema entra por la transmisión. Suele traducirse en una mente orientada a explicar bien lo que se ha aprendido, con paciencia para el detalle y para repetirlo las veces que haga falta, y con poca tolerancia a la explicación vaga. Puede aparecer también impaciencia cuando el otro no pone de su parte, porque el esfuerzo de enseñar se mide contra el esfuerzo de atender. Se observa en qué has aprendido y no has transmitido todavía a nadie, y en cómo reaccionas cuando alguien pregunta lo mismo por tercera vez.",
    venus: "El valor se mide por lo que se aporta. Puede manifestarse como una dificultad concreta para cobrar, para recibir o para que alguien haga algo por uno sin devolverlo en la misma moneda. Los vínculos se sostienen haciendo, y ahí funcionan bien; lo que cuesta es estar sin hacer nada, porque sin tarea la relación parece quedarse sin sustento. Se observa en cuándo fue la última vez que aceptaste algo sin devolver nada, y en qué haces con las manos cuando estás con alguien a quien quieres.",
    marte: "La acción se organiza como oficio. Suele traducirse en una capacidad de empezar y terminar que no depende del entusiasmo, y en poca tolerancia con quien no cumple lo que dijo que haría. El límite está en decir que no: la tarea se coge antes de haber comprobado si corresponde, porque comprobarlo llevaría más tiempo que hacerla. Se observa en cuántas cosas has asumido este mes que no te tocaban, y en cuántas veces has terminado tú la parte que otro dejó a medias sin decírselo.",
    jupiter: "El sentido se encuentra en la contribución. Puede manifestarse como generosidad práctica y como una tendencia a asumir más de lo que cabe, porque el criterio para aceptar es si hace falta y no si es sostenible. Eso construye una reputación sólida y una agenda que no se corresponde con las horas disponibles, de modo que lo que falla no es la voluntad sino la aritmética. Se observa en el desajuste entre lo comprometido y las horas reales de tu semana, y en qué has tenido que cancelar últimamente.",
    saturno: "Es la combinación más concentrada de este portal: la disciplina entrando por la función de la disciplina. Suele traducirse en una exigencia alta y constante que se aplica sobre todo hacia dentro, y en competencias construidas a lo largo de años que otros dan por naturales. El riesgo es un cansancio que no se nombra hasta que el cuerpo lo impone, porque reconocerlo antes parecería una excusa. Se observa en cuánto te exiges comparado con lo que exigirías a otro en tu misma situación.",
    urano: "El oficio entra en tensión con la diferencia. Puede manifestarse como una manera propia de hacer las cosas que no encaja con el procedimiento establecido, sostenida con la misma constancia con que otros sostienen la norma. Produce innovación real y fricción con las estructuras, porque la discrepancia no es ocasional sino metódica y por tanto más difícil de ignorar. Se observa en qué normas incumples de forma sistemática y con criterio, y en cuántas de ellas has conseguido que se cambien.",
    neptuno: "El servicio entra por la sensibilidad. Suele traducirse en una dedicación que no mide el coste y en dificultad para distinguir entre ayudar y hacerse cargo de un proceso que no es propio. La entrega puede volverse difusa: se sostiene algo sin saber exactamente qué se está sosteniendo ni hasta cuándo, porque no hay una tarea con final. Se observa en a quién estás sosteniendo en algo que solo esa persona puede atravesar, y en qué tendría que pasar para que consideraras que tu parte terminó.",
    pluton: "El compromiso no admite término medio. Puede manifestarse como una dedicación total a una tarea o a una causa, y como dificultad para soltarla cuando ha terminado, porque soltar se parece demasiado a traicionar. Aparece también control sobre cómo se hacen las cosas: delegar implica aceptar que salgan de otra manera, y esa otra manera se vive como peor. Se observa en qué sigues sosteniendo mucho después de que dejara de tener sentido, y en qué tareas no has delegado nunca.",
    nodo_norte: "La dirección menos automática pasa por recibir. Dentro de esta metodología señala que pedir ayuda, descansar sin justificarlo y aceptar sin devolver es el territorio que enseña. Suele dar pereza y no urgencia, de modo que se pospone indefinidamente sin que parezca que se está evitando nada: simplemente nunca es el momento. Se observa en cuánto tardas en pedir algo que te vendría bien, y en qué sientes exactamente en el momento de pedirlo, antes de que el otro responda.",
    nodo_sur: "El terreno practicado es la responsabilidad. Es un recurso real —se puede contar contigo y lo sabe todo el mundo— y también el refugio: asumir una tarea más es la manera conocida de no mirar otra cosa, y tiene la ventaja de que nadie lo cuestiona porque desde fuera parece diligencia. Se observa en qué te pones a hacer cuando hay algo pendiente que te incomoda, y en cuántas de tus tareas actuales elegirías hoy si pudieras empezar de cero.",
    ascendente: "El tema está en la entrada. Suele traducirse en aparecer en las situaciones desde la función: preguntando qué hace falta, ofreciéndose, tomando una tarea antes de que nadie la reparta. Da fiabilidad inmediata y hace que a uno se le pida mucho desde el principio, porque el entorno aprende rápido que ahí hay alguien que responde. Se observa en lo primero que haces al llegar a un sitio nuevo, y en cuánto tiempo pasa antes de que alguien te encargue algo.",
    medio_cielo: "La contribución pública es la transmisión de un oficio. Puede manifestarse en enseñar, formar o dejar algo que otros usarán sin conocer a su autor: manuales, métodos, maneras de hacer que sobreviven a quien las montó. Es una aportación que se reconoce tarde y a veces no se reconoce, porque cuanto mejor está hecha menos se nota que alguien la hizo. Se observa en qué te gustaría que quedara de lo que haces, y en cuánto de eso ya está en manos de otro.",
  },

  arcturus: {
    sol: "La identidad se organiza alrededor de comprender. Suele traducirse en reconocerse a uno mismo por la capacidad de ver cómo funcionan las cosas, con la claridad que eso da y el punto ciego correspondiente: no entender algo se vive como un fallo personal en vez de como una situación normal. Eso hace difícil pedir explicaciones y fácil fingir que ya se había entendido. Se observa en cómo reaccionas cuando algo se te resiste, y en cuántas veces has asentido sin haber seguido del todo lo que te decían.",
    luna: "La estructura entra por la vía emocional. Puede manifestarse como necesidad de que las cosas tengan sentido para poder estar tranquilo, y como inquietud sostenida mientras algo queda sin explicación. El pensamiento se usa para regular el estado de ánimo: entender funciona como consuelo, y por eso lo que no se deja entender resulta especialmente difícil de sostener. Se observa en qué haces cuando algo te remueve y no sabes por qué, y en cuánto necesitas entender un conflicto antes de poder dormir.",
    mercurio: "Es la combinación más directa de este portal: la mente entrando por la función de la mente. Suele traducirse en una capacidad alta de ver el patrón debajo de los casos y de explicarlo con precisión, a veces antes de que al otro le interese saberlo. El riesgo es explicar cuando lo que hacía falta era escuchar, y no notar la diferencia porque desde dentro ambas cosas se sienten como ayudar. Se observa en cuántas veces esta semana diste una solución que no te habían pedido.",
    venus: "El vínculo se comprende antes que se habita. Puede manifestarse como una tendencia a analizar una relación en vez de estar en ella, y como atracción por personas que resultan interesantes de entender, que no siempre son las que acompañan. Lo que suele faltar no es comprensión sino presencia: se sabe mucho del otro y se está poco con él. Se observa en cuánto tiempo dedicas a pensar sobre una relación comparado con el que pasas dentro de ella sin evaluarla.",
    marte: "La acción se supedita al diseño. Suele traducirse en no empezar hasta que el plan esté claro, con la calidad que eso da y el coste de que muchas cosas no lleguen a empezar nunca, porque el plan admite siempre una versión mejor. Puede aparecer impaciencia con procesos que avanzan más lento que el entendimiento, que son casi todos. Se observa en qué tienes diseñado y sin ejecutar, y en cuánto tiempo llevan esos proyectos en esa fase.",
    jupiter: "El sentido se encuentra en la comprensión amplia. Puede manifestarse como una curiosidad que abarca campos muy distintos y como la tendencia a explicar con entusiasmo lo que se acaba de entender, a veces antes de haberlo asentado. El riesgo es quedarse en la estructura y perder el interés justo cuando empieza la aplicación, que es la parte lenta y sin descubrimientos. Se observa en cuántos temas has entendido y abandonado, y en cuántos de ellos llegaste a usar para algo.",
    saturno: "La arquitectura se vuelve oficio. Suele traducirse en construir sistemas que aguantan porque están bien pensados, y en una exigencia alta sobre la coherencia interna de lo que se hace: una excepción mal resuelta molesta más que un fallo grande y visible. Puede aparecer rigidez cuando la realidad no respeta el diseño, que es siempre. Se observa en qué te cuesta más, si que algo falle o que falle de una manera que no habías previsto.",
    urano: "El patrón se ve para romperlo. Puede manifestarse como una capacidad de detectar qué supuesto está sosteniendo una estructura y de proponer otro distinto, con la incomodidad que eso genera alrededor: cuestionar el supuesto obliga a todos a revisar lo construido encima. Produce ideas que tardan en aceptarse y que a veces se adoptan años después sin atribución. Se observa en qué has propuesto que se rechazó y más tarde se hizo.",
    neptuno: "La comprensión entra por lo difuso. Suele traducirse en intuir la estructura de algo antes de poder demostrarla, y en dificultad para explicar cómo se llegó a esa conclusión, lo que hace que se reciba como opinión y no como análisis. Puede aparecer también sobreinterpretación: ver patrones donde solo hay coincidencia, precisamente porque el ojo está entrenado para encontrarlos. Se observa en cuántas de tus intuiciones estructurales has comprobado después.",
    pluton: "El entendimiento se vuelve un asunto de fondo. Puede manifestarse como la necesidad de llegar a la raíz de algo sin poder dejarlo a medias, y como una lucidez sobre las dinámicas de poder que otros no ven o prefieren no nombrar. Aparece control a través del conocimiento: saber más es una forma de no quedar expuesto. Se observa en qué situación estás analizando en lugar de atravesar, y en qué información guardas que podrías compartir.",
    nodo_norte: "La dirección menos automática pasa por lo concreto. Dentro de esta metodología señala que ejecutar sin tenerlo resuelto, y acompañar sin explicar, es el territorio que enseña. Suele sentirse como un retroceso: hacer algo sin entenderlo del todo parece impropio, y estar presente sin aportar análisis parece no estar haciendo nada. Se observa en qué proyecto empezarías si aceptaras que la primera versión va a salir imperfecta.",
    nodo_sur: "El terreno practicado es comprender. Es un recurso real y potente —se llega al fondo de las cosas— y también el refugio: entender una situación es la manera conocida de no tener que estar dentro de ella, y tiene la ventaja de que parece trabajo serio. Nadie discute a quien está analizando. Se observa en qué analizas cuando lo que tocaba era responder, y en cuántas conversaciones difíciles has convertido en un problema interesante.",
    ascendente: "El tema está en la puerta. Suele traducirse en entrar en las situaciones observando y ordenando antes de participar, lo que da una presencia serena y una distancia que algunos leen como frialdad o como evaluación. La primera impresión es de alguien que está midiendo, aunque por dentro solo se esté situando. Se observa en cuánto tardas en decir algo al llegar a un grupo nuevo, y en qué dice de ti la gente que te conoció hace poco.",
    medio_cielo: "La contribución pública es dejar estructuras que sirvan. Puede manifestarse en sistemas, métodos o formas de organizar que otros utilizan sin saber quién los pensó, porque una estructura bien hecha se vuelve invisible en cuanto funciona. Es una aportación duradera y poco visible, y conviene estar en paz con eso antes de emprenderla. Se observa en qué has dejado montado que sigue funcionando sin ti, y en si alguien sabe que fue tuyo.",
  },
}
