// CARTOGRAFÍA ESTELAR 144 — cruces portal × punto natal (3 de 4).
//
// CAPA B. Alfa Centauri, Antares y Regulus.

import type { PuntoNatalId } from "../domain/types"

export const CRUCES_3: Record<string, Record<PuntoNatalId, string>> = {
  alfa_centauri: {
    sol: "Lo cercano forma parte de aquello con lo que la persona se identifica. Suele traducirse en reconocerse por lo que se hace de verdad y no por lo que se proyecta, con la solidez que eso da y con una desconfianza hacia lo que no se puede tocar ni comprobar. Puede aparecer dificultad para valorar lo propio si no ha producido algo visible, de modo que un año entero de aprendizaje cuenta menos que una estantería montada. Se observa en cómo describes tu año: por lo hecho o por lo vivido.",
    luna: "La proximidad entra por la vía menos deliberada. Puede manifestarse como una necesidad fuerte de casa, rutina y presencia física para estar tranquilo, y como inquietud cuando eso falta, aunque todo lo demás vaya bien. El afecto se recibe mejor haciendo cosas juntos que hablando, de modo que una conversación larga puede dejar menos que una tarde compartida en silencio. Se observa en qué necesitas físicamente al final de un día difícil.",
    mercurio: "El tema entra por lo concreto. Suele traducirse en una mente práctica que pregunta cómo se hace antes que por qué, y que desconfía de lo que no se puede ejemplificar con un caso. Es una defensa muy eficaz contra la palabrería y un límite cuando lo importante todavía no es concreto: las ideas en formación no sobreviven a esa pregunta. Se observa en qué ideas has descartado por no saber cómo se harían, y en cuántas de ellas siguen sin hacerse.",
    venus: "El valor está en lo que se comparte a diario. Puede manifestarse como vínculos construidos sobre convivencia y tareas compartidas más que sobre conversación, con la estabilidad que eso da y con una discreción que a veces se lee como distancia. Lo que falta no es afecto sino decirlo, porque hacerlo parece suficiente y no siempre lo es para el otro. Se observa en cuándo fue la última vez que dijiste en voz alta lo que alguien te importa.",
    marte: "La acción entra por lo inmediato. Suele traducirse en resolver rápido lo que está delante, con una eficacia real que el entorno agradece, y en usar esa misma eficacia para no mirar lo que pide una decisión mayor. La ventaja es que nadie lo llama evitación: desde fuera parece responsabilidad. Se observa en qué ordenaste, arreglaste o resolviste la última vez que tenías algo importante pendiente, y en cuánto duró esa actividad.",
    jupiter: "El crecimiento pasa por lo práctico. Puede manifestarse como una capacidad de convertir una idea grande en algo que funciona, y como una expansión que no se nota porque ocurre despacio y en el terreno, sin anuncios. Eso acumula más de lo que parece y se reconoce tarde, incluso por uno mismo. Se observa en qué has construido que empezó siendo muy pequeño, y en si llegaste a proponértelo o simplemente fue creciendo.",
    saturno: "La encarnación se vuelve oficio. Suele traducirse en sostener la infraestructura de una vida —propia o de otros— durante años, con fiabilidad total y poco reconocimiento, porque lo que funciona no se comenta. Puede aparecer también rigidez con lo cotidiano: los cambios en la rutina cuestan más de lo que su tamaño justificaría. Se observa en qué se descolocaría mañana si dejaras de hacer lo que haces cada día sin pensarlo.",
    urano: "Lo cercano entra en tensión con la ruptura. Puede manifestarse como cambios súbitos en el entorno inmediato —mudanzas, reorganizaciones, cortes con lo doméstico— que contrastan con una vida por lo demás muy estable, y que sorprenden a quien te conoce. No son inconstancia: son la única vía por la que sale lo que no cabía en la rutina. Se observa en qué has cambiado de golpe en tu vida cotidiana y qué lo precedió.",
    neptuno: "Lo concreto entra por lo difuso. Suele traducirse en una sensibilidad física alta: se registra el ambiente de un lugar, el cansancio ajeno, lo que no está dicho dentro de una casa, y se registra por el cuerpo antes que por la cabeza. Puede aparecer también confusión entre cuidar y absorber, porque atender a alguien y cargar con su estado empiezan igual. Se observa en cómo te deja estar en el espacio de otra persona.",
    pluton: "La proximidad se vuelve un asunto de fondo. Puede manifestarse como una intensidad puesta en el entorno inmediato —la casa, la familia, lo diario— y como control sobre ese territorio, que se defiende con más fuerza de la que su importancia aparente justifica. Es el sitio donde no se admite que otro decida. Se observa en qué parte de tu vida cotidiana no toleras que otro organice, y en qué pasa cuando alguien lo intenta.",
    nodo_norte: "La dirección menos automática pasa por lo grande. Dentro de esta metodología señala que atender lo que excede el radio conocido, y decidir sin tenerlo todo concretado, es el territorio que enseña. Suele posponerse resolviendo cosas pequeñas, que siempre hay, y que además dejan la sensación legítima de haber hecho algo. Se observa en qué decisión grande llevas aplazada y en qué has hecho hoy en su lugar.",
    nodo_sur: "El terreno practicado es lo concreto. Es un recurso real —se sabe hacer que las cosas funcionen, y eso sostiene a mucha gente— y también el refugio: ocuparse de lo inmediato es la manera conocida de no mirar lo que pide más, y tiene la ventaja de que produce resultados visibles el mismo día. Se observa en qué tarea práctica buscas cuando hay algo sin resolver, y en cuánto alivio te da terminarla.",
    ascendente: "El tema está en la puerta. Suele traducirse en entrar en las situaciones por lo práctico: qué hace falta, dónde se pone uno, qué se puede hacer para que aquello funcione. Da una presencia útil y discreta que la gente agradece sin señalarla, y que puede hacer que te asignen tareas antes de que te pregunten tu opinión. Se observa en qué haces con las manos al llegar a un sitio nuevo.",
    medio_cielo: "La contribución pública es hacer que las cosas ocurran. Puede manifestarse en un papel de ejecución donde lo que otros proponen se vuelve real, función poco visible mientras existe y muy echada en falta en cuanto desaparece. El reconocimiento suele ir a quien tuvo la idea, no a quien la hizo posible. Se observa en qué se pararía si tú no estuvieras, y en si alguien de tu entorno sabría decirlo.",
  },

  antares: {
    sol: "La intensidad forma parte de aquello con lo que la persona se identifica. Suele traducirse en reconocerse por vivir las cosas a fondo, con la honestidad que eso impone —cuesta mucho fingir— y con el coste de que poco resulta suficiente. Puede aparecer desprecio hacia lo tibio, incluido lo tibio propio, lo que deja poco margen para las etapas normales de cualquier proceso. Se observa en qué sientes ante algo que simplemente te da igual.",
    luna: "La intensidad entra por la vía menos deliberada. Puede manifestarse como respuestas emocionales grandes y rápidas, que llegan antes de cualquier evaluación y que otros encuentran desproporcionadas al hecho que las provocó. No es una elección: ocurre antes, y la proporción solo se recupera un rato después, cuando ya se dijo o se hizo algo. Se observa en cuánto tardas en recuperar el estado normal después de algo que te remueve.",
    mercurio: "El tema entra por la mente. Suele traducirse en un pensamiento que va al fondo y que no se conforma con la versión oficial de nada, con la lucidez que eso da y con la dificultad de detenerse una vez empezado. Puede aparecer también insistencia mental sobre lo ya cerrado: se sigue buscando la pieza que falta en algo que ya no admite conclusión. Se observa en cuántas veces repasas una conversación terminada.",
    venus: "El vínculo no admite término medio. Puede manifestarse como relaciones profundas y rápidas, con poca zona intermedia entre estar dentro y estar fuera, y con dificultad para sostener las formas intermedias de afecto que la mayoría de la gente usa a diario. Lo que se ofrece es una lealtad total; lo que cuesta es la tregua, el rato sin fondo. Se observa en con quién puedes estar tranquilo sin sentir que es superficial.",
    marte: "La voluntad entra directamente en la acción. Suele traducirse en una capacidad de empuje poco común y en poca tolerancia a la resistencia, propia o ajena, de modo que la respuesta a un obstáculo es más fuerza antes que otra estrategia. El límite es aplicar toda esa fuerza a algo que no la pedía, y descubrir el desgaste después. Se observa en dónde apretaste más y funcionó peor, y en si lo repetiste.",
    jupiter: "El sentido se encuentra en lo que transforma. Puede manifestarse como atracción por procesos de cambio profundo, propios o de otros, y como dificultad con lo que solo mejora un poco, que es la mayor parte de lo que se puede hacer. Eso lleva a abandonar mejoras reales por no parecer suficientes. Se observa en qué proyectos abandonas por parecerte insuficientes, y en dónde estarían ahora si los hubieras sostenido.",
    saturno: "La intensidad se vuelve oficio. Suele traducirse en sostener durante años algo exigente que otros no aguantarían, con una competencia construida a base de atravesar y no de estudiar. Puede aparecer dureza consigo mismo: lo que se le concede a otro no se concede a uno, porque uno sabe lo que podría aguantar. Se observa en qué has sostenido que te costó de verdad, y en si alguien supo lo que te costaba.",
    urano: "La transformación entra por la ruptura. Puede manifestarse como cambios radicales ejecutados de golpe, sin fase intermedia, que reordenan una vida entera en poco tiempo. Produce libertad real y deja daños alrededor, porque la velocidad no deja espacio para que los demás se ajusten ni para revisar qué se lleva uno. Se observa en qué rompiste entero pudiendo haber revisado una parte.",
    neptuno: "La intensidad entra por lo difuso. Suele traducirse en una sensibilidad muy alta a lo no dicho y a los procesos ajenos, con dificultad para distinguir dónde termina uno y empieza el otro cuando el asunto es grave. Puede aparecer entrega total a algo idealizado, sostenida más allá de lo que el objeto real merecía. Se observa en qué proceso ajeno estás viviendo como propio, y en quién te lo ha señalado.",
    pluton: "Es la combinación más concentrada de este portal: la intensidad entrando por la función de la intensidad. Suele traducirse en una capacidad alta de atravesar lo difícil, propio o acompañando, y en una relación con el control que conviene mirar de frente, porque desde dentro se experimenta como responsabilidad y no como control. Se observa en qué estás intentando controlar porque no soportas no saber cómo termina.",
    nodo_norte: "La dirección menos automática pasa por soltar. Dentro de esta metodología señala que dejar ir un proceso sin haberlo cerrado a tu manera es el territorio que enseña. Suele sentirse como abandono, o como dejar a alguien tirado, y esa lectura llega tan rápido que impide comprobar si es cierta. Se observa en qué proceso terminó hace tiempo y sigues sosteniendo, y en qué crees que pasaría si lo soltaras.",
    nodo_sur: "El terreno practicado es la intensidad. Es un recurso real —se sabe estar donde otros no pueden, y eso hace falta— y también el refugio: subir la intensidad es la manera conocida de no estar en la incertidumbre, porque dentro de algo intenso no queda espacio para la duda. Se observa en qué haces cuando algo queda sin resolver, y en si lo que haces resuelve algo o solo lo llena.",
    ascendente: "El tema está en la puerta. Suele traducirse en una presencia que se nota al entrar aunque no se hable, y en respuestas iniciales más fuertes de lo que la situación pedía, que después hay que matizar. Eso genera reacciones claras en los demás desde el primer momento: rara vez indiferencia. Se observa en cómo describe la gente su primera impresión de ti, y en cuánto se parece a lo que eres después.",
    medio_cielo: "La contribución pública pasa por acompañar lo que otros no pueden mirar. Puede manifestarse en trabajos o papeles ligados a procesos duros, donde la intensidad propia es exactamente lo que hace falta y no un exceso. Es un sitio donde uno encaja por fin, con el riesgo de que se convierta en el único sitio. Se observa en qué situaciones te busca la gente, y en si te buscan también para las alegres.",
  },

  regulus: {
    sol: "El lugar de referencia forma parte de aquello con lo que la persona se identifica. Suele traducirse en reconocerse por lo que se sostiene para otros, con la generosidad que eso implica y con el punto ciego correspondiente: el efecto que se tiene deja de notarse justo cuando es mayor, porque se vuelve el fondo habitual de las situaciones. Se observa en qué pasa en una conversación justo después de que tú hablas.",
    luna: "La visibilidad entra por la vía menos deliberada. Puede manifestarse como una necesidad de que lo que se hace sea reconocido para sentirse tranquilo, y como un malestar difuso cuando no lo es, incluso sabiendo con certeza que el trabajo estuvo bien. La confirmación no es vanidad: funciona como regulación, y por eso su ausencia se nota tanto. Se observa en cómo te quedas cuando nadie comenta algo que hiciste bien.",
    mercurio: "El tema entra por la palabra. Suele traducirse en que lo que se dice pesa más de lo que quien lo dice calcula: un comentario de pasada se recuerda durante años, una opinión cierra un debate que seguía abierto. Aporta claridad y exige medir, porque el mismo mecanismo funciona igual cuando uno habla cansado o molesto. Se observa en qué frase tuya te han citado años después, y en si la recordabas.",
    venus: "El valor pasa por lo que se da. Puede manifestarse como generosidad real y como un desnivel silencioso en los vínculos, donde uno da y el otro recibe: cómodo para ambos durante mucho tiempo y empobrecedor para los dos, porque uno no aprende a pedir y el otro no aprende a sostener. Se observa en quién te ha ayudado a ti este año, con algo que costara.",
    marte: "La acción se ejerce desde el frente. Suele traducirse en tomar la iniciativa con naturalidad y en acabar organizando cosas que no se iba a organizar, simplemente porque nadie más empezó y a uno le sale. El límite es ocupar el sitio que otro necesitaba para desarrollarse, y no notarlo porque desde dentro solo se ve la tarea resuelta. Se observa en cuántas veces decidiste por un grupo sin proponerlo.",
    jupiter: "El sentido se encuentra en dar cobertura. Puede manifestarse como una generosidad que abre puertas a otros y como la tendencia a prometer apoyo por encima de lo sostenible, porque en el momento de ofrecerlo la capacidad parece ilimitada. Lo que falla después no es la intención sino la disponibilidad. Se observa en a cuántas personas les has ofrecido ayuda que todavía no has podido dar.",
    saturno: "El liderazgo se vuelve oficio. Suele traducirse en sostener una responsabilidad pública durante años, respondiendo por decisiones propias y también por las que heredó, con la autoridad que eso construye y el peso que acumula sin descargarse nunca. Dejar el puesto se vuelve difícil aunque ya no se quiera. Se observa en qué papel sostienes que ya no se parece a lo que quieres, y en qué te impide soltarlo.",
    urano: "La referencia entra en tensión con la ruptura. Puede manifestarse como ocupar un lugar visible de una manera que no se corresponde con lo que ese lugar espera, con el desconcierto que eso genera alrededor y con el margen que abre para quien venga detrás. La incomodidad inicial es el precio de haber cambiado la forma del puesto. Se observa en qué haces distinto a lo que se espera de tu posición.",
    neptuno: "El liderazgo entra por lo difuso. Suele traducirse en una influencia que opera por presencia y no por palabra, difícil de medir para quien la ejerce y por tanto difícil de administrar. Aparece también idealización por parte de otros, que cuesta corregir porque corregirla exige decepcionar a propósito. Se observa en qué esperan de ti que tú nunca ofreciste, y en cuándo empezaron a esperarlo.",
    pluton: "El poder se vuelve un asunto de fondo. Puede manifestarse como una conciencia aguda de las dinámicas de autoridad —quién decide de verdad, qué se está negociando debajo de la conversación— y como una relación intensa con el control del propio terreno. Conviene mirarla de frente, porque no reconocerla no la desactiva. Se observa en qué parte de tu influencia no has reconocido nunca en voz alta.",
    nodo_norte: "La dirección menos automática pasa por ceder el sitio. Dentro de esta metodología señala que dejar que otro ocupe el centro, y contribuir sin que conste, es el territorio que enseña. Suele sentirse como desaparecer, y esa sensación es tan desagradable que se evita sin llegar a formular que se está evitando. Se observa en cuándo cediste el sitio por última vez, y en qué hiciste mientras otro lo ocupaba.",
    nodo_sur: "El terreno practicado es ocupar el centro. Es un recurso real —se sabe sostener a un grupo, dar seguridad, decidir cuando hace falta— y también el refugio: ponerse al frente es la manera conocida de no tener que estar en un sitio sin papel definido, que resulta mucho más incómodo. Se observa en qué haces en un grupo donde no eres la referencia, y en cuánto tardas en irte.",
    ascendente: "El tema está en la puerta. Suele traducirse en una entrada que reorganiza el ambiente sin proponérselo: cambia el tono, se abre espacio, la gente se coloca respecto a ti antes de que hayas dicho nada. Es un efecto que no se puede apagar y que conviene conocer para no atribuirlo a otra cosa. Se observa en qué pasa en una sala cuando llegas, mirando a los demás y no a ti.",
    medio_cielo: "Es una combinación especialmente pública: la contribución es el lugar de referencia mismo. Puede manifestarse en un papel visible donde lo que se hace afecta a mucha gente, y donde las decisiones pequeñas tienen consecuencias que no se ven desde el escritorio. El peso no está en el cargo sino en el número de personas que ajustan algo suyo según lo que tú decides. Se observa en cuántas son.",
  },
}
