// CARTOGRAFÍA ESTELAR 144 — cruces portal × punto natal (2 de 4).
//
// CAPA B. Lyra, Orión y Andrómeda.

import type { PuntoNatalId } from "../domain/types"

export const CRUCES_2: Record<string, Record<PuntoNatalId, string>> = {
  lyra: {
    sol: "La autonomía forma parte de aquello con lo que la persona se identifica. Suele traducirse en una noción de uno mismo ligada a no deber nada y a haberse hecho por cuenta propia, con la fuerza que eso da y la trampa correspondiente: aceptar ayuda se vive como una grieta en la propia definición, no como una circunstancia. Por eso el rechazo suele ser inmediato y anterior a cualquier cálculo. Se observa en qué sientes cuando alguien te ofrece algo que efectivamente necesitas.",
    luna: "La soberanía entra por la vía menos deliberada. Puede manifestarse como una necesidad de espacio propio para estar tranquilo y como una reacción inmediata de retirada cuando alguien se acerca demasiado, más rápida que cualquier decisión. No se elige: el cuerpo se aparta y la explicación llega después, ya construida. Se observa en qué hace tu cuerpo cuando alguien invade tu tiempo o tu sitio, y en cuánto tardas en recuperar el tono después de un día entero acompañado.",
    mercurio: "El tema entra por el criterio propio. Suele traducirse en una mente que no adopta una idea hasta haberla comprobado por su cuenta, con la independencia que eso da y la lentitud que impone: todo hay que volver a recorrerlo. Puede aparecer también dificultad para aprender de alguien, porque aceptar una explicación se parece a ceder terreno. Se observa en cuántas cosas has aceptado este año solo porque alguien con autoridad las dijo, y en cuántas fuentes consultas antes de dar algo por bueno.",
    venus: "El valor se mide por la libertad que algo deja. Puede manifestarse como atracción por vínculos que no piden renuncia y como incomodidad rápida con los que la piden, incluso cuando esa renuncia es pequeña y razonable. Lo que se ofrece es lealtad sin fusión, que es una forma sólida de querer y que no todo el mundo reconoce como tal. Se observa en qué te hace empezar a pensar en irte de una relación, y en si esa señal ha sido la misma en todas.",
    marte: "La acción es propia y no delegada. Suele traducirse en empezar cosas sin esperar permiso ni respaldo, con la capacidad real de crear que eso implica y con la carga de trabajo que conlleva. El límite está en el reparto: se hace solo lo que habría salido mejor con dos personas, y el coste no se contabiliza porque pedir habría costado más. Se observa en qué estás haciendo por tu cuenta que podrías compartir, y en cuántas veces has rehecho algo que otro ya había hecho.",
    jupiter: "El crecimiento pasa por ampliar el margen propio. Puede manifestarse como una confianza alta en la propia capacidad para arreglárselas y como la tendencia a asumir proyectos completos en solitario, porque desde fuera parecen abarcables. El riesgo es sobrestimar lo que cabe en una sola persona, y descubrirlo cuando ya no hay margen para pedir ayuda sin quedar mal. Se observa en cuántas veces has tenido que rescatar algo tuyo a última hora y en soledad.",
    saturno: "La autonomía se vuelve oficio. Suele traducirse en construir algo propio durante años sin respaldo externo, con la solidez que eso da y el aislamiento que acumula despacio, sin un momento identificable en que empezara. Puede aparecer orgullo en no haber pedido nunca nada, que es la forma más eficaz de asegurarse de seguir sin pedir. Se observa en cuánto te costaría, hoy y en concreto, pedir ayuda con una cosa pequeña.",
    urano: "La soberanía entra por la ruptura. Puede manifestarse como decisiones de cambio tomadas sin consulta y ejecutadas rápido, que desde fuera parecen impulsivas y por dentro llevaban meses o años madurando en silencio. Esa asimetría hace que el entorno reaccione con sorpresa y que uno se sienta incomprendido, cuando lo que faltó fue avisar. Se observa en cómo terminaron tus últimos cambios importantes, y en a quién se lo contaste antes.",
    neptuno: "La independencia entra por lo difuso. Suele traducirse en idealizar la propia libertad hasta hacerla incompatible con cualquier compromiso concreto, porque ninguno alcanza la versión imaginada. Aparece también dificultad para distinguir entre necesitar espacio y estar evitando algo, ya que ambas cosas se sienten igual desde dentro y la primera es una razón aceptable. Se observa en qué evitas exactamente cuando necesitas espacio, si lo miras sin dar la respuesta rápida.",
    pluton: "La autonomía se vuelve un asunto de fondo. Puede manifestarse como una intolerancia profunda a que alguien tenga poder sobre las decisiones propias, incluso en formas menores y pactadas, y como cortes radicales cuando eso ocurre. La reacción es desproporcionada respecto al hecho concreto porque no responde al hecho sino a lo que representa. Se observa en qué relaciones has terminado enteras por una parte concreta que podría haberse negociado.",
    nodo_norte: "La dirección menos automática pasa por depender. Dentro de esta metodología señala que construir con alguien, aceptar ayuda y quedarse a negociar es el territorio que enseña. Suele sentirse como pérdida antes que como ganancia, y esa sensación llega antes de cualquier evidencia, de modo que se confunde con un aviso. Se observa en de qué te has ido para no tener que negociar, y en qué habría hecho falta concretamente para que te quedaras.",
    nodo_sur: "El terreno practicado es arreglárselas solo. Es un recurso real —se sale adelante en condiciones en que otros se bloquean— y también el refugio: hacerlo por cuenta propia es la manera conocida de no exponerse a que alguien falle, y tiene la ventaja de que el resultado depende solo de uno. Se observa en qué haces siempre tú aunque haya quien podría hacerlo, y en qué te dices en el momento de decidir no pedirlo.",
    ascendente: "El tema está en la puerta. Suele traducirse en entrar en las situaciones marcando distancia y criterio desde el principio, lo que da una presencia definida y hace que cueste acercarse: el gesto inicial dice claramente hasta dónde. Eso filtra mucho y también aleja a gente que habría encajado. Se observa en qué muestras primero al conocer a alguien, y en cuánto tiempo pasa hasta que alguien te tutea de verdad.",
    medio_cielo: "La contribución pública es abrir camino donde no lo había. Puede manifestarse en haber creado algo que no existía o en ocupar un lugar que nadie había ocupado antes, sin referencia previa ni manual. El límite es que un camino abierto en solitario suele quedar sin recorrer: nadie más sabe cómo se hizo. Se observa en qué has creado y en quién más, aparte de ti, sabría sostenerlo mañana.",
  },

  orion: {
    sol: "La polaridad forma parte de aquello con lo que la persona se identifica. Suele traducirse en reconocerse por la capacidad de sostener posiciones difíciles y de decidir lo que otros evitan, con el peso que eso implica y con el prestigio silencioso que trae. Puede aparecer también la necesidad de que haya algo en juego para sentirse presente, de modo que la calma se vive como ausencia. Se observa en cómo te sientes en una situación donde no hay nada que resolver.",
    luna: "El conflicto entra por la vía menos deliberada. Puede manifestarse como una alerta emocional constante ante cualquier tensión en el ambiente, detectada antes de que se declare, y como más comodidad en una situación difícil que en una tranquila, porque la calma no resulta fiable y se espera lo que viene después. Se observa en cómo duermes cuando todo va bien, y en qué haces con la inquietud que aparece justo entonces.",
    mercurio: "El tema entra por el discernimiento. Suele traducirse en una mente que distingue con precisión las dos posiciones de un asunto y que formula lo incómodo con exactitud, a menudo en la frase que nadie quería decir. El riesgo es tener razón en el contenido y equivocarse en el momento, y no registrar la diferencia porque el contenido sigue siendo cierto al día siguiente. Se observa en qué conversación ganaste y salió mal igualmente.",
    venus: "El vínculo se organiza alrededor de la tensión. Puede manifestarse como atracción por relaciones intensas donde hay algo que resolver, y como dificultad para sostener lo que ya está en paz: cuando desaparece el problema compartido, cuesta saber qué queda. Eso lleva a reabrir asuntos cerrados sin intención consciente de hacerlo. Se observa en qué te ocurre cuando una relación se vuelve tranquila, y en cuánto dura esa etapa.",
    marte: "La acción entra en el conflicto directamente. Suele traducirse en capacidad de sostener un enfrentamiento sin desbordarse y de poner límites con claridad, lo que resulta muy útil cuando hace falta y desproporcionado cuando no. El límite es anticipar el conflicto y responder a uno que todavía no ha ocurrido, de modo que la respuesta llega antes que el hecho y a veces lo provoca. Se observa en cuántas discusiones has tenido mentalmente antes de tenerlas.",
    jupiter: "El sentido se encuentra en la integración de lo contrario. Puede manifestarse como una comprensión amplia que sostiene posiciones opuestas sin necesitar descartar ninguna, y como la tendencia a convertir cualquier asunto en una cuestión de principios, incluidos los que no lo eran. Eso agranda conversaciones pequeñas y agota a quien solo quería resolver algo concreto. Se observa en cuántas veces una discusión menor se te volvió de fondo.",
    saturno: "El discernimiento se vuelve oficio. Suele traducirse en asumir las decisiones difíciles que nadie firma y en sostener sus consecuencias durante años, incluidas las que salieron mal. Da autoridad real y acumula un desgaste que no se reparte, porque quien decide carga solo con la parte impopular mientras el beneficio se distribuye. Se observa en cuántas decisiones de tu entorno llevan tu firma, y en cuántas de ellas te siguen reprochando.",
    urano: "La polaridad entra por la ruptura. Puede manifestarse como la capacidad de nombrar en voz alta lo que un grupo evita, con el efecto liberador y el coste social que eso tiene: quien dice lo que todos piensan queda después asociado al problema. Produce cambios reales y aislamiento, con frecuencia a la vez. Se observa en qué dijiste que nadie quería decir, y en qué pasó contigo en ese grupo los meses siguientes.",
    neptuno: "El conflicto entra por lo difuso. Suele traducirse en percibir tensiones antes de que se declaren, sin poder señalar de dónde salen ni aportar pruebas, lo que deja a uno con una certeza que no puede compartir. Aparece dificultad para saber si el conflicto es real o anticipado, porque ambas cosas producen la misma sensación. Se observa en cuántas de las tensiones que percibiste se confirmaron después.",
    pluton: "La integración del conflicto se vuelve un asunto de fondo. Puede manifestarse como una capacidad de atravesar situaciones que a otros los destruyen, y como una tendencia a que las cosas se vuelvan de vida o muerte cuando no lo eran: el desacuerdo escala hasta un terreno donde ya no se puede retroceder sin pérdida. Se observa en qué desacuerdo se te convirtió en ruptura total, y en si podrías reconstruir cómo llegó a serlo.",
    nodo_norte: "La dirección menos automática pasa por la paz. Dentro de esta metodología señala que sostener una situación sin tensión, sin buscarle el conflicto latente, es el territorio que enseña. Suele resultar aburrido antes que tranquilo, y ese aburrimiento se interpreta como señal de que algo falta, cuando es solo la desacostumbre. Se observa en qué haces cuando no hay nada que resolver, y en cuánto tardas en encontrar algo.",
    nodo_sur: "El terreno practicado es el conflicto. Es un recurso real —se sabe estar donde otros no aguantan y decidir cuando nadie quiere— y también el refugio: entrar en tensión es la manera conocida de sentirse presente y despierto, más fiable que cualquier otra. Por eso se busca sin reconocerlo como búsqueda. Se observa en qué buscas cuando te sientes desconectado, y en qué tipo de conversación te devuelve la energía.",
    ascendente: "El tema está en la puerta. Suele traducirse en entrar en las situaciones evaluando posiciones y detectando dónde está el desacuerdo, lo que da una presencia alerta que algunos leen como desconfianza y otros como criterio. En ambos casos, lo que se percibe primero es que estás midiendo. Se observa en qué es lo primero que registras al entrar en una reunión, y en qué dice de ti quien te conoció en una situación tensa.",
    medio_cielo: "La contribución pública pasa por sostener lo difícil. Puede manifestarse en un papel donde se toman o se median decisiones que otros no quieren, con el reconocimiento tardío que eso suele tener: se agradece años después, si se agradece. Mientras dura, lo que llega es el reproche de ambas partes. Se observa en para qué te llaman cuando hay un problema, y en si te llaman también cuando no lo hay.",
  },

  andromeda: {
    sol: "La libertad forma parte de aquello con lo que la persona se identifica. Suele traducirse en una noción de uno mismo ligada al margen disponible: mientras quede la posibilidad de irse, se está bien, aunque no se use nunca. Puede aparecer dificultad para reconocerse dentro de un compromiso largo, porque la definición propia incluía no estar atado. Se observa en qué sientes al firmar algo por varios años, y en si esa sensación cambia cuando ya está firmado.",
    luna: "La necesidad de espacio entra por la vía menos deliberada. Puede manifestarse como inquietud física en situaciones cerradas y como un alivio inmediato al saber que hay salida, aunque no se contemple usarla. No es una decisión: aparece antes, y la razón se construye después para justificarla. Se observa en qué hace tu cuerpo en un compromiso del que no puedes salir, y en qué buscas con la mirada al entrar en una habitación.",
    mercurio: "El tema entra por la perspectiva. Suele traducirse en una mente que sitúa cualquier asunto dentro de un marco más grande, lo que devuelve proporción y también quita urgencia a lo que la tenía de verdad. Puede llegar antes de que el otro esté listo para recibirlo, y entonces lo que era alivio se recibe como quitarle importancia a su problema. Se observa en cuántas veces has dado perspectiva a alguien que quería compañía.",
    venus: "El valor se mide por lo que no cierra puertas. Puede manifestarse como atracción por vínculos con margen y como pérdida de interés cuando empieza la rutina compartida, que es justo cuando la relación empezaba a asentarse. Lo que se ofrece es apertura y lo que falta es continuidad, y esa combinación resulta muy atractiva al principio y poco fiable después. Se observa en qué fase de tus relaciones sueles perder interés.",
    marte: "La acción busca terreno nuevo. Suele traducirse en energía alta para empezar en sitios donde no hay nada montado y baja para mantener lo ya montado, de modo que el trabajo difícil se hace y el fácil se abandona. El límite es que casi todo lo importante ocurre en la fase de mantenimiento, que es la que no tiene descubrimientos. Se observa en cuántas cosas dejaste justo cuando pedían constancia y no imaginación.",
    jupiter: "Es una combinación especialmente expansiva: el sentido se encuentra en ampliar. Puede manifestarse en viajes, estudios o proyectos de gran alcance, y en la tendencia a abrir más de lo que se puede desarrollar, porque abrir es barato y desarrollar no. Eso deja un paisaje de comienzos prometedores sin continuación, que desde fuera parece dispersión y desde dentro parece riqueza. Se observa en cuántas cosas tienes abiertas ahora y cuántas avanzan.",
    saturno: "La libertad entra en tensión con la estructura. Suele traducirse en una relación difícil con los compromisos largos: se cumplen, y pesan más de lo que pesarían a otro, porque cada día de cumplimiento se nota. Puede producir también una libertad construida con disciplina —margen ganado a base de orden—, que es la versión sólida de este cruce y la menos frecuente. Se observa en qué compromiso sostienes y en cuánto te cuesta sostenerlo.",
    urano: "La expansión entra por la ruptura. Puede manifestarse como cambios de vida súbitos que desde fuera parecen huidas y desde dentro son decisiones largamente maduradas, que solo se ejecutan cuando ya no admiten discusión. Produce libertad real y vínculos dejados a medias, porque la ejecución rápida no deja tiempo para cerrar nada. Se observa en cómo cerraste tus últimos cambios grandes, y en con quién no volviste a hablar.",
    neptuno: "La perspectiva entra por lo difuso. Suele traducirse en una sensación de posibilidad amplia que no termina de concretarse en nada, y en dificultad para distinguir entre tener visión y no haber decidido, porque ambas cosas se viven como tener el futuro abierto. La diferencia está en si existe un primer paso con fecha. Se observa en cuántas de tus posibilidades abiertas tienen un primer paso definido y cuántas solo tienen entusiasmo.",
    pluton: "La libertad se vuelve un asunto de fondo. Puede manifestarse como una intolerancia profunda a sentirse atrapado y como cortes radicales cuando eso ocurre, incluso a costa de cosas valiosas que estaban dentro del paquete. La decisión es rápida y completa porque revisar una parte implicaría quedarse, y quedarse es lo que no se tolera. Se observa en qué has quemado entero por no poder revisar una parte.",
    nodo_norte: "La dirección menos automática pasa por quedarse. Dentro de esta metodología señala que sostener algo concreto el tiempo suficiente para que pese es el territorio que enseña. Suele sentirse como renuncia, y esa sensación aparece justo cuando la cosa empieza a pedir constancia, de modo que se confunde con una señal de que no era. Se observa en qué llevas evitando comprometerte y sabes que quieres.",
    nodo_sur: "El terreno practicado es marcharse. Es un recurso real —se reconoce cuándo algo se ha acabado, antes que la mayoría— y también el refugio: irse es la manera conocida de no tener que atravesar lo difícil, y siempre hay una lectura de ciclo disponible para justificarlo. Por eso cuesta distinguir el acierto de la costumbre. Se observa en qué haces cuando una situación se complica, contando desde el primer impulso.",
    ascendente: "El tema está en la puerta. Suele traducirse en entrar en las situaciones con ligereza y sin comprometerse de entrada, lo que da una presencia cómoda y deja al otro sin saber si estás realmente ahí. Esa ambigüedad inicial resulta agradable y hace que nadie cuente contigo del todo. Se observa en cuánto tardas en decir si vas a algo, y en cuántas veces te lo han tenido que preguntar dos veces.",
    medio_cielo: "La contribución pública es traer lo que estaba fuera del horizonte. Puede manifestarse en un papel donde se aporta una referencia, una experiencia o una idea que el entorno no tenía y no sabía que le faltaba. El valor es real y difícil de defender, porque nadie echaba de menos aquello antes de que llegara. Se observa en qué has traído a tu grupo que no estaba antes, y en si se reconoce como tuyo.",
  },
}
